---
title: ""
author: "Duc-Quang Nguyen | swissinfo.ch"
date: " 2017"
output: 
  html_document:
    toc: true
    toc_depth: 3
    theme: simplex
---

Forcats: https://blog.exploratory.io/why-factor-is-one-of-the-most-amazing-things-in-r-e967fe27d292
http://stackoverflow.com/questions/36066931/rotate-d3-parset-visualization-90-degrees-make-horizontal-instead-of-vertical


```{r setup, include=FALSE}
wrangleAggregate <- F

data.file.2016 <- "data/yearlyAsylum_eurostat_2016.csv"
data.sub.file <- "input/yearlyAsylum_eurostat_2016_aggregated.csv"

library(readr)
library(tidyr)
library(dplyr)
library(magrittr)
library(countrycode)
library(ggplot2)
library(scales)
library(swiMap)
library(swiTheme)
library(forcats)

### Interactive 
# library(htmltools)
# library(swiRcharts)
# library(rCharts)

```

```{r get & wrangle data}
data <- read.csv(data.file.2016) %>% 
  filter(sex == "Total", age == "Total", asyl_app == "First time applicant") %>%
  select(-sex, -age, -asyl_app, -unit, -time)
```  

```{r wrangle more}
iso2agg <- c("EU28", "TOTAL")
citizenAgg <- c("Total", "European Union (28 countries)", "Extra-EU-28")
if(wrangleAggregate) {
  # remove aggregates
  dat <- data %>% filter(!iso2 %in% iso2agg)
  
  dat %<>% filter(!citizen %in% citizenAgg, !iso2 %in% iso2agg) %>%
    group_by(iso2, geo, citizen) %>% dplyr::summarise(tot = sum(values, na.rm = T )) %>% ungroup()
  
  # remove coutry of origin always 0
  citToRemove <- as.character(unlist(dat %>% group_by(citizen) %>% dplyr::summarise(grandTot = sum(tot, na.rm = T)) %>% filter(grandTot == 0) %>% select(citizen)))
  dat %<>% filter(!citizen %in% citToRemove)
  
  ### Get the top country of origins and destinations
  ntop <- 9
  
  sumByGeo <- dat %>% group_by(iso2) %>% dplyr::summarise(sumByGeo = sum(tot, na.rm = T)) %>% ungroup() %>% arrange(desc(sumByGeo))
  iso2.top <- sumByGeo %>% select(iso2) %>% head(ntop) %>% unlist(use.names = F) %>% as.character()
  
  sumByCit <- dat %>% group_by(citizen) %>% dplyr::summarise(sumByCit = sum(tot, na.rm = T)) %>% ungroup() %>% arrange(desc(sumByCit))
  cit.top <- sumByCit %>% select(citizen) %>% head(ntop) %>% unlist(use.names = F) %>% as.character()
  
  
  ### Merge not top countries
  df <- dat
  df$iso2 <- ifelse(as.character(df$iso2) %in% iso2.top, as.character(df$iso2), 'other')
  df$citizen <- ifelse(as.character(df$citizen) %in% cit.top, as.character(df$citizen), 'Other countries')
  
  df %<>% group_by(iso2, citizen) %>% dplyr::summarise (values = sum(tot, na.rm = T)) %>% ungroup()
  
  # add back the country names to merged iso2
  df$geo <- as.character(unlist(dat[match(df$iso2, dat$iso2),'geo']))
  df[which(df$iso2 == "other"), 'geo'] <- "Other European countries"
  
  # drop unused levels
  df$citizen <- factor(df$citizen)
  df$iso2 <- factor(df$iso2)
  
  citLength <- unlist(unique(df %>% group_by(iso2) %>% dplyr::summarise(nelem = length(values)) %>% select(nelem)))
  geoLength <- unlist(unique(df %>% group_by(citizen) %>% dplyr::summarise(nelem = length(values)) %>% select(nelem)))
  
  stopifnot(geoLength == length(iso2.top) + 1, citLength == ntop + 1)
  
  ## tmp hack for long country names
  df$geo <- gsub(" \\(.*\\)$", "", df$geo)
  df$citizen <- gsub(" \\(.*\\)$", "", df$citizen)
  
  data  %>% filter(iso2 == "TOTAL", citizen == "Total") %>% select(values) %>% dplyr::summarise(sum(values))
  
  write.csv(df, file = data.sub.file, row.names = F)  
} else {
  df <- read.csv(file = data.sub.file)    
}

```

## Viz!

```{r parset}
library(parsetR)
library(swiRcharts)
library(htmlwidgets)
ps.chart <- parset(select(df, citizen, geo, values),
                   dimensions = c('citizen', 'geo'),
                   # use some JavaScript to inform parset that Freq has the value
                   # http://www.buildingwidgets.com/blog/2015/9/17/week-37-parsetr
                   value = htmlwidgets::JS("function(d){return d.values}"),
                   tension = 0.7, width = "100%", height = 500,
                   spacing = 57
)

  # overwite default padding
  ps.chart$sizingPolicy$padding <- 4
  #ps.chart$sizingPolicy$defaultHeight <- "100%"
  
  
  saveWidget(ps.chart, file = "asylum_parsetH.html", selfcontained = FALSE, libdir = "js")

  swi_widget("asylum_parsetH.html", "asylum_parsetSankifed.html"
  #  h2 = txt["title",lang],
  #  descr = txt["description",lang],
  #  h3 = paste0(txt["subtitle", lang]),
    # source = paste0(txt["source",lang], ": ",
    #   htmlLink("http://ec.europa.eu/eurostat/en/web/products-datasets/-/MIGR_ASYAPPCTZM",
    #   txt["eurostat",lang])),
    # author = paste0(txt["credit",lang], ": ",
    #   htmlLink("https://github.com/timelyportfolio/parsetR", "parsetR"), " | ",
    #   htmlLink("http://www.swissinfo.ch", "swissinfo.ch")),
    # footer = paste0("<strong>",
    #   txt["footer.title",lang], "</strong><br>", txt["footer",lang])
  )

  #Make it horizontal!
  ori.file <- list.files("js/d3-parsets-1.2.4", "d3.parsets.min.js", full.names = T)
  file.copy(from = list.files(system.file("extdata", package="swiRcharts"),
       "d3.parsets_horizontal.js", full.names = T), ori.file, overwrite = T)
  
  
  ori.file <- list.files("js/parset-binding-0.0.1", "parset.js", full.names = T)
  file.copy(from = list.files(system.file("extdata", package="swiRcharts"),
       "parset_horizontal.js", full.names = T), ori.file, overwrite = T)
  
```